[Match]
ImageId=os-image

[Output]
Format=disk
ImageId=os-image
UnifiedKernelImages=auto
SplitArtifacts=uki

# since we're using a uki (a single bootable .efi file), we don't need these extra split artifacts
# which were generated in the base-with-kernel phase
RemoveFiles=/boot/efi/????????????????????????????????,/boot/????????????????????????????????

[Content]
Bootable=yes
BaseTrees=%O/base-with-kernel

[Config]
Dependencies=base-with-kernel
